- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Start Apache Service
    service:
      name: httpd
      state: started

  - name: install the latest version of unzip
    yum:
      name: unzip
      state: latest 

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
       src:  https://www.free-css.com/assets/files/free-css-templates/download/page263/dpot.zip
       dest: /tmp
       remote_src: yes

  -  name: Copy files 
     copy:
       src: /tmp/dpot
       dest: /var/www/html/
       remote_src: yes 

  -  name: Restart service httpd, in all cases
     service:
       name: httpd
       state: restarted
       









     

